"""Create initial core tables

Revision ID: 0cdb7e103849
Revises: 
Create Date: 2026-09-05 11:18:41.210339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cdb7e103849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_owners_village_id'), 'owners', ['village_id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pashu_aadhaar_id', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_owner_id'), 'animals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_animals_pashu_aadhaar_id'), 'animals', ['pashu_aadhaar_id'], unique=True)
    op.create_index(op.f('ix_animals_village_id'), 'animals', ['village_id'], unique=False)
    op.create_table('disease_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_reports_animal_id'), 'disease_reports', ['animal_id'], unique=False)
    op.create_index(op.f('ix_disease_reports_created_at'), 'disease_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_disease_reports_reported_by'), 'disease_reports', ['reported_by'], unique=False)
    op.create_index(op.f('ix_disease_reports_status'), 'disease_reports', ['status'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_disease', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['disease_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_report_id'), 'ai_predictions', ['report_id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_vet', sa.UUID(), nullable=True),
    sa.Column('assigned_worker', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vet'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_worker'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['disease_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_assigned_vet'), 'cases', ['assigned_vet'], unique=False)
    op.create_index(op.f('ix_cases_assigned_worker'), 'cases', ['assigned_worker'], unique=False)
    op.create_index(op.f('ix_cases_report_id'), 'cases', ['report_id'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_report_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_worker'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_vet'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_ai_predictions_report_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_disease_reports_status'), table_name='disease_reports')
    op.drop_index(op.f('ix_disease_reports_reported_by'), table_name='disease_reports')
    op.drop_index(op.f('ix_disease_reports_created_at'), table_name='disease_reports')
    op.drop_index(op.f('ix_disease_reports_animal_id'), table_name='disease_reports')
    op.drop_table('disease_reports')
    op.drop_index(op.f('ix_animals_village_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_pashu_aadhaar_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_owner_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_owners_village_id'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('villages')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
